### ISSUE TITLE
How to control dynamixel after srv/JointCommand.srv is not available?

### ISSUE THREAD

**Issue by Leung555** [ROBOTIS-GIT/dynamixel-workbench-msgs#17]
In the Previous version, I used JointCommand.h to include in my c++ code to control the motor.
Now, Is there any different on how to control the motor.

**Comment by yhna** [comment]
@Leung555 
Sorry for late reply.
There is no difference in how to control the motor.
JointCommand.srv uses a motor angle value(rad) of float32 type.
Currently, DynamixelCommand.srv uses protocol value of int32 type.
This is to handle other commands in Dynamixel with the same DynamixelCommand.srv
